# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:

all:
  sf_admin_dash:
    web_dir:                      /sfAdminDashPlugin
    image_dir:                    /sfAdminDashPlugin/images/icons/
    default_image:                config.png
    resize_mode:                  thumbnail
    site:                         @brigo
    include_path:                 true
    include_jquery_no_conflict:   false
    logout:                       true
    login_route:                  @sf_guard_signin
    logout_route:                 @sf_guard_signout
    categories:
      Acolhidos:
        items:
          Listar:
            url:          acolhido/index
            image:        users.png
            credentials:  [[admin, publisher]]
          Incluir:
            url:          acolhido/new
            image:        users.png
            credentials:  [[admin, publisher]]
          Escolaridade:
            url:          escolaridade_acolhido/index
            image:        users.png
            credentials:  [[admin, publisher]]
          Cursos Externos:
            url:          curso_externo_acolhido/index
            image:        users.png
            credentials:  [[admin, publisher]]
          Apadrinhamento:
            url:          apadrinhamento/index
            image:        users.png
            credentials:  [[admin, publisher]]
          Entradas e Saidas:
            url:          entradas_e_saidas/index
            image:        users.png
            credentials:  [[admin, publisher]]
          Entidades Passadas:
            url:          entidades_passadas_acolhido/index
            image:        users.png
            credentials:  [[admin, publisher]]
      Responsáveis:
        items:
          Listar:
            url:          responsavel/index
            image:        language.png
            credentials:  [admin]
          Incluir:
            url:          responsavel/new
            image:        language.png
            credentials:  [admin]
      Padrinhos:
        items:
          Listar:
            url:          padrinho/index
            image:        language.png
            credentials:  [admin]
          Incluir:
            url:          padrinho/new
            image:        language.png
            credentials:  [admin]
      Voluntarios:
        items:
          Listar:
            url:          voluntario/index
            image:        language.png
            credentials:  [admin]
          Incluir:
            url:          voluntario/new
            image:        language.png
            credentials:  [admin]


