generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CursoExternoAcolhido
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          curso_externo_acolhido
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: 
        nomeEscola: {label: Nome da escola, attributes: { size:  50 }}
        nomeCurso: {label: Nome do curso, attributes: { size:  50 }}
        dataConclusao: {label: Data de conclusão, date_format:<center> dd/MM/yyyy </center>}
        descricao: {label: Descrição do curso, attributes: {rows: 10, cols: 50}}
        acolhidoNome: {label: Acolhido}
       
        
      list: 
        title: Cursos externos registrados
        display: [=acolhidoNome, nomeCurso, dataConclusao]  
      filter: 
        display: [acolhido_id, nomeCurso, descricao, nomeEscola, dataConclusao] 
      form: ~
      edit:
        title: Editando o curso externo %%nomeCurso%% do acolhido: %%acolhidoNome%%
        fields:
          
      new:
        title: Novo curso externo
        fields:
         
      
