all:
  .settings:
    enabled_modules: [sfGuardAuth]
    login_module:           sfGuardAuth
    login_action:           signin
    secure_module:          sfGuardAuth
    secure_action:          secure
    i18n: on 
    default_culture: pt_BR
