generator:
  class: sfDoctrineGenerator
  param:
    model_class:           EntradasESaidasAcolhido
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          entradas_e_saidas_acolhido_entradas_e_saidas
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        mae_id: {label: Mãe}
        responsavel_id: {label: Responsável}
        voluntario_id: {label: Voluntário}
        dataSaida: {label: Saída, date_format:<center> dd/MM/yyyy <br> hh:mm:ss </center>}
        dataPrevistaRetorno: {label: Previsão retorno, date_format:<center> dd/MM/yyyy <br> hh:mm:ss </center>}
        dataRetorno: {label: Retorno, date_format:<center> dd/MM/yyyy <br> hh:mm:ss </center>}
        observacoes: {label: Observações}
        situacao: {label: Situação}
      list:
        title: Entradas e Saídas dos acolhidos
        display: [=acolhido, dataSaida, dataPrevistaRetorno, dataRetorno]  
      filter:
        display: [acolhido_id, situacao, mae_id, pai_id, responsavel_id, voluntario_id, padrinho_id, dataSaida, dataPrevistaRetorno, dataRetorno, observacoes]
      form:    ~
      edit:    ~
      new:     ~
